- hosts: localhost
  tasks:
  - name: install deps
    become: true
    become_user: root
    apt:
      pkg:
        - docker
        - docker-compose
        - git
  - name: delete prior dir
    become: true
    become_user: root
    shell: rm -rf projcwebserv
  - name:  clone git repo
    become: true
    become_user: root
    shell: git clone https://github.com/agski331/proj_c_webserv_pub.git projcwebserv
  - name: run docker compose
    shell: docker-compose up -d
    become: true
    become_user: root
    args:
      chdir: ./projcwebserv
    #docker_compose:
    #  project_src: ./projcwebserv
    register: output
  - debug:
      var: output
